# Generated by Django 5.2.11 on 2026-10-05 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('handling', models.CharField(choices=[('agent', 'Agent'), ('needs_human', 'Needs a person'), ('with_staff', 'With staff')], default='agent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponseEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('content', models.TextField()),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.CreateModel(
            name='CommentEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.CreateModel(
            name='HandoffEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('handling', models.CharField(choices=[('agent', 'Agent'), ('needs_human', 'Needs a person'), ('with_staff', 'With staff')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.CreateModel(
            name='ReasoningEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('step', models.CharField(blank=True, max_length=40)),
                ('content', models.TextField()),
                ('decision', models.CharField(blank=True, max_length=60)),
                ('model_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.CreateModel(
            name='StatusChangeEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('old_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.CreateModel(
            name='ToolCallEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('tool', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='PendingToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('arguments', models.JSONField(default=dict)),
                ('arguments_schema', models.JSONField(default=dict)),
                ('unknown_arguments', models.JSONField(default=list)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tool_call', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.TextField()),
                ('findings', models.JSONField(default=list)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reply', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now=True)),
                ('waiting', models.BooleanField(default=False)),
                ('waiting_question', models.TextField(blank=True)),
                ('waiting_user_id', models.UUIDField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to=settings.AUTH_USER_MODEL)),
                ('old_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__766ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='tickets_tic_created_c2132d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketrun',
            constraint=models.UniqueConstraint(fields=('ticket', 'visibility'), name='one_run_per_ticket_lane'),
        ),
    ]
