# Generated by Django 5.2.11 on 2026-10-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_pendingreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=10),
        ),
    ]
