# Generated by Django 5.2.11 on 2026-10-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_backfill_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('handling', models.CharField(choices=[('agent', 'Agent'), ('needs_human', 'Needs a person'), ('with_staff', 'With staff')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='handling',
            field=models.CharField(choices=[('agent', 'Agent'), ('needs_human', 'Needs a person'), ('with_staff', 'With staff')], default='agent', max_length=20),
        ),
    ]
