# Generated by Django 5.2.11 on 2026-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_handoffevent_ticket_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreply',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
