# Generated by Django 5.2.11 on 2026-10-03 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_pendingreply_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('arguments', models.JSONField(default=dict)),
                ('arguments_schema', models.JSONField(default=dict)),
                ('unknown_arguments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tool_call', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
