# Generated by Django 5.2.11 on 2026-10-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_pendingtoolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('tool', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
    ]
