# Generated by Django 5.2.11 on 2026-10-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_toolcallevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticketevent')),
                ('content', models.TextField()),
                ('decision', models.CharField(blank=True, max_length=60)),
                ('model_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticketevent',),
        ),
    ]
