# Generated by Django 5.2.11 on 2026-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_reasoningevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoningevent',
            name='step',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
