# Generated by Django 5.2.11 on 2026-10-04 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_reasoningevent_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now=True)),
                ('waiting', models.BooleanField(default=False)),
                ('waiting_question', models.TextField(blank=True)),
                ('waiting_user_id', models.UUIDField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tickets.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ticket', 'visibility'), name='one_run_per_ticket_lane')],
            },
        ),
    ]
