# Generated by Django 5.2.11 on 2026-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtoolcall',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', max_length=10),
        ),
    ]
