/**
 * What the reviewer changed, and what to send back.
 *
 * The form itself is generated by `AutoForm` from the Zod schema that
 * `zodFromJsonSchema` derives from the proposal, so nothing here builds fields
 * or parses inputs any more - Zod does both. What is left is the part specific
 * to the gate: telling an approval from a correction.
 *
 * Only changed fields count as a correction. Re-sending every field would turn
 * the reviewer's normalisation into an edit the agent is told about, and the
 * "corrected" badge would be on every approval.
 */

import type { z } from 'zod';

type Values = Record<string, unknown>;

/** Fields whose value differs from what the assistant proposed. */
export function corrections(
  schema: z.ZodObject<z.ZodRawShape>,
  values: Values,
  proposed: Values | undefined,
): Values {
  const changed: Values = {};
  for (const name of Object.keys(schema.shape)) {
    const before = proposed?.[name];
    const after = values[name];
    if (same(before, after)) continue;
    changed[name] = after;
  }
  return changed;
}

/** Empty and absent are the same thing on a form the reviewer never filled. */
function same(before: unknown, after: unknown): boolean {
  const left = before ?? '';
  const right = after ?? '';
  return left === right;
}

/**
 * What goes on the wire: nothing when nothing changed, the whole argument set
 * otherwise.
 *
 * The gate replaces the proposed arguments wholesale, so a partial object would
 * drop the fields the reviewer left alone. Built from the schema's own keys, so
 * an argument the tool does not accept cannot be smuggled back in - it is not
 * on the form, so the reviewer never saw it and has not approved it.
 */
export function decisionArguments(
  schema: z.ZodObject<z.ZodRawShape>,
  values: Values,
  proposed: Values | undefined,
): Values {
  if (Object.keys(corrections(schema, values, proposed)).length === 0)
    return {};

  const args: Values = {};
  for (const name of Object.keys(schema.shape)) {
    const value = values[name] ?? proposed?.[name];
    if (value !== undefined && value !== '') args[name] = value;
  }
  return args;
}
