# Generated by Django 5.2.11 on 2026-09-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_modelpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpreference',
            name='purpose',
            field=models.CharField(choices=[('decision', 'Decision'), ('answer', 'Answer')], max_length=20),
        ),
    ]
