# Generated by Django 5.2.11 on 2026-10-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modelpreference_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpreference',
            options={'ordering': ['purpose']},
        ),
    ]
