# Generated by Django 5.2.11 on 2026-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunCursor',
            fields=[
                ('run_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'agent run cursor',
                'verbose_name_plural': 'agent run cursors',
            },
        ),
    ]
